# Generated by Django 5.0.6 on 2026-04-25 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu')], default='en', max_length=5)),
                ('income_category', models.CharField(blank=True, choices=[('bpl', 'BPL'), ('low', 'Low'), ('mid', 'Middle'), ('high', 'High')], max_length=10)),
                ('occupation', models.CharField(blank=True, choices=[('labour', 'Daily Wage'), ('farmer', 'Farmer'), ('private', 'Private'), ('govt', 'Govt'), ('self', 'Self Employed')], max_length=20)),
                ('health_conditions', models.JSONField(default=list)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
