# Generated by Django 5.0.6 on 2026-04-25 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('central', 'Central'), ('state', 'State')], max_length=10)),
                ('states', models.JSONField(default=list)),
                ('benefit_amount', models.CharField(max_length=200)),
                ('benefit_description', models.TextField()),
                ('eligibility_rules', models.JSONField(default=dict)),
                ('applicable_to', models.JSONField(default=list)),
                ('apply_link', models.URLField(blank=True)),
                ('helpline', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
