# Generated by Django 5.0.6 on 2026-04-25 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('flow_level', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', max_length=10)),
                ('cramp_score', models.IntegerField(default=5)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('cycle_length', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='auth_app.userprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
