# Generated by Django 5.0.6 on 2026-04-25 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lmp_date', models.DateField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('baby_gender', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy', to='auth_app.userprofile')),
            ],
        ),
    ]
