# Generated by Django 5.0.6 on 2026-04-25 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=15)),
                ('food_items', models.JSONField(default=list)),
                ('total_calories', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('photo_ai', 'Photo AI'), ('search', 'Search')], default='manual', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='auth_app.userprofile')),
            ],
        ),
    ]
